matrix:
  include:
    - os: linux
      language: python
      python: 2.6
      services:
        - mongodb
        - redis-server
    - os: linux
      language: python
      python: 2.7
      services:
        - mongodb
        - redis-server
    - os: linux
      language: python
      python: 3.3
      services:
        - mongodb
        - redis-server
    - os: linux
      language: python
      python: 3.4
      services:
        - mongodb
        - redis-server
    - os: linux
      language: python
      python: 3.5
      services:
        - mongodb
        - redis-server
    - os: linux
      language: python
      python: nightly
      services:
        - mongodb
        - redis-server
    - os: osx
      language: objective-c
      env:
        - PYTHON_VERSION=2.6
    - os: osx
      language: objective-c
      env:
        - PYTHON_VERSION=2.7
    - os: osx
      language: objective-c
      env:
        - PYTHON_VERSION=3.3
    - os: osx
      language: objective-c
      env:
        - PYTHON_VERSION=3.4
    - os: osx
      language: objective-c
      env:
        - PYTHON_VERSION=3.5

install:
  - "source travis/install.sh"

script:
  - flake8 werobot
  - coverage run --source=werobot setup.py -q nosetests

after_success: coveralls

notifications:
  email: false
