os: osx
language: generic
osx_image: xcode8.2  # macOS 10.12
env:
  - PYTHON_VERSION=2 PYTHON_INSTALL_METHOD=system
matrix:
  include:
    - env:
      - PYTHON_VERSION="2"
      - PYTHON_INSTALL_METHOD=tox
    - env:
      - PYTHON_VERSION="3"
      - PYTHON_INSTALL_METHOD=tox
    - env:
      - PYTHON_VERSION=2.7
      - PYTHON_INSTALL_METHOD=macpython
    - env:
      - PYTHON_VERSION=3.4
      - PYTHON_INSTALL_METHOD=macpython
    - env:
      - PYTHON_VERSION=3.5
      - PYTHON_INSTALL_METHOD=macpython
    - osx_image: xcode8  # OS X 10.11
    - osx_image: xcode6.4 # OS X 10.10
cache:
  directories:
  - $HOME/.pyenv

after_script: set +e

install:
  - "source travis/install.sh"

script:
  - "source travis/script.sh"

after_script: set +e

after_success:
  - pip install codecov
  - codecov

notifications:
  email: false
