os: osx
language: generic
osx_image: xcode7.3  # OS X 10.11
env:
  - PYTHON_VERSION=system
matrix:
  include:
    - env:
      - PYTHON_VERSION=tox
    - env:
      - PYTHON_VERSION=2.7
      - PYTHON_INSTALL_METHOD=macpython
    - env:
      - PYTHON_VERSION=3.3
      - PYTHON_INSTALL_METHOD=macpython
    - env:
      - PYTHON_VERSION=3.4
      - PYTHON_INSTALL_METHOD=macpython
    - env:
      - PYTHON_VERSION=3.5
      - PYTHON_INSTALL_METHOD=macpython
    - env:
      - PYTHON_VERSION=2
      - PYTHON_INSTALL_METHOD=homebrew
    - env:
      - PYTHON_VERSION=3
      - PYTHON_INSTALL_METHOD=homebrew
    - osx_image: xcode7  # 10.10
    - osx_image: beta-xcode6.2  # OS X 10.9

install:
  - "source travis/install.sh"

script:
  - "source travis/script.sh"

after_success:
  - pip install codecov
  - codecov

addons:
    code_climate:
        repo_token: 060f1934a00d41f8e52fd6b4c5298f2528e5164bfe708bd46614fd05f913f521

notifications:
  email: false
