os: osx
language: generic
env:
  matrix:
matrix:
  include:
    - env:
        - PYTHON_VERSION=2.6
        - PYTHON_INSTALL_METHOD=macports
    - env:
        - PYTHON_VERSION=2.7
        - PYTHON_INSTALL_METHOD=macpython
    - env:
        - PYTHON_VERSION=3.3
        - PYTHON_INSTALL_METHOD=macpython
    - env:
        - PYTHON_VERSION=3.4
        - PYTHON_INSTALL_METHOD=macpython
    - env:
        - PYTHON_VERSION=3.5
        - PYTHON_INSTALL_METHOD=macpython
    - env:
        - PYTHON_VERSION=2
        - PYTHON_INSTALL_METHOD=system
    - env:
        - PYTHON_VERSION=2
        - PYTHON_INSTALL_METHOD=homebrew
    - env:
        - PYTHON_VERSION=3
        - PYTHON_INSTALL_METHOD=homebrew


install:
  - "source travis/install.sh"
  - python --version

script:
  - coverage run --source werobot -m py.test

after_success:
  - pip install codecov
  - codecov

notifications:
  email: false
