version: '{branch}-{build}'
build: off
cache:
  - '%LOCALAPPDATA%\pip\Cache'
services:
  - mongodb
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - ps: "ls C:/Python*"
install:
  - C:\Python35\python -m pip install tox
  - choco install redis-64
  - redis-server --service-install
  - redis-server --service-start

test_script:
  - C:\Python35\python -m tox -e py26
  - C:\Python35\python -m tox -e py27
  - C:\Python35\python -m tox -e py33
  - C:\Python35\python -m tox -e py34
  - C:\Python35\python -m tox -e py35
on_success:
  - set PATH=C:\\Python35;C:\\Python35\\Scripts;%PATH%
  - pip install codecov coverage
  - codecov
on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*
#after_test:
#  - "%PYTHON%/Scripts/codecov"
